version: '3'

services:
    nginx:
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
