version: '3'

services:
    nginx:
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "443:443"
            - "80:80"
        env_file:
            - .env
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
    
    db:
        build: ./requirements/mariadb
        image: mariadb
        container_name: mariadb
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=wordpress
        volumes:
            - database:/var/lib/mysql

volumes:
    database:
        driver: local
        driver_opts:
            type: nome
            device: /home/lfrasson/data/mysql
            o: bind
