version: '3'

services:
    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        container_name: mariadb
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - 42-network
    
    wordpress:
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - MYSQL_HOST=mariadb:3306
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - wordpress:/var/www/lfrasson/wordpress
        networks:
            - 42-network

    nginx:
        depends_on:
            - wordpress
        build: ./requirements/nginx
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "443:443"
        env_file:
            - .env
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
        volumes:
            - wordpress:/var/www/lfrasson/wordpress
        networks:
            - 42-network

volumes:
    dbdata:
        external: true
    wordpress:
        external: true

networks:
    42-network:
        driver: bridge
